// Industrial environment and cinematic rendering for Mine Descent.
export class IndustrialArt {
  constructor(T,renderer){this.T=T;this.renderer=renderer;this.dust=[];this.effects=[];this.moving=[];this.roomLights=[];this.materials={};this.sharedGeometries=new Set();this.tex={};this.glows=new Map();this.obstacles=[];this.initMaterials();}
  v(x=0,y=0,z=0){return new this.T.Vector3(x,y,z);}
  texture(url){const T=this.T;let t;if(typeof Image==='function'){t=new T.TextureLoader().load(url);t.userData.path=url;}else{t=new T.DataTexture(new Uint8Array([165,165,165,255]),1,1);t.needsUpdate=true;t.userData.path=url;}t.wrapS=t.wrapT=T.RepeatWrapping;t.colorSpace=T.SRGBColorSpace;t.anisotropy=Math.min(8,this.renderer.capabilities?.getMaxAnisotropy?.()||1);return t;}
  material(name,options){const m=new this.T.MeshStandardMaterial(options);m.userData.shared=true;this.materials[name]=m;return m;}
  initMaterials(){const T=this.T;this.tex.rock=this.texture('/rock.jpg');this.tex.metal=this.texture('/metal.jpg');this.material('rock',{color:0x9a948a,map:this.tex.rock,bumpMap:this.tex.rock,bumpScale:.5,roughness:.98,metalness:.06});this.material('armor',{color:0x6c7377,map:this.tex.metal,bumpMap:this.tex.metal,bumpScale:.065,roughness:.62,metalness:.75});this.material('steel',{color:0x848b90,map:this.tex.metal,bumpMap:this.tex.metal,bumpScale:.035,roughness:.42,metalness:.86});this.material('rubber',{color:0x171b1e,roughness:.97,metalness:.12});this.material('brass',{color:0x7a6550,map:this.tex.metal,bumpMap:this.tex.metal,bumpScale:.03,roughness:.67,metalness:.7});this.material('yellow',{color:0x998555,map:this.tex.metal,roughness:.78,metalness:.55});this.material('floor',{color:0x454a49,map:this.tex.metal,bumpMap:this.tex.metal,bumpScale:.14,roughness:.87,metalness:.72});this.material('ceramic',{color:0x4c5455,roughness:.84,metalness:.28});this.material('black',{color:0x090b0d,roughness:.8,metalness:.18});}
  mesh(parent,geo,mat,pos,scale){const m=new this.T.Mesh(geo,mat);if(pos)m.position.copy(pos);if(scale)m.scale.copy(scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  box(parent,pos,size,mat=this.materials.armor){const g=new this.T.BoxGeometry(...size),uv=g.attributes.uv;for(let f=0;f<6;f++){const a=f<2?size[2]:size[0],b=f<2?size[1]:f<4?size[2]:size[1];for(let j=0;j<4;j++){const i=f*4+j;uv.setXY(i,uv.getX(i)*Math.max(a/4,.25),uv.getY(i)*Math.max(b/4,.25));}}return this.mesh(parent,g,mat,this.v(...pos));}
  cylinder(parent,a,b,r,mat=this.materials.steel,segments=10,r2=r){const av=this.v(...a),bv=this.v(...b),d=bv.clone().sub(av);const m=this.mesh(parent,new this.T.CylinderGeometry(r2,r,d.length(),segments),mat,av.clone().add(bv).multiplyScalar(.5));m.quaternion.setFromUnitVectors(this.v(0,1,0),d.normalize());return m;}
  emissive(color,intensity=1){const key=color+':'+intensity;if(this.glows.has(key))return this.glows.get(key);const m=new this.T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:intensity,roughness:.3,metalness:.2});m.userData.shared=true;this.glows.set(key,m);return m;}
  noise(x,y,z=0){return Math.sin(x*.53+y*.78+z*.9)*.52+Math.sin(x*1.37-y*.91+z*.42)*.24+Math.sin(x*3.4+y*2.5-z*1.7)*.1;}
  wall(parent,center,axis,sign,opening,wallList,roomIndex){const T=this.T,other=[0,1,2].filter(i=>i!==axis),normal=this.v();normal.setComponent(axis,-sign);const base=center.clone();base.setComponent(axis,base.getComponent(axis)+sign*18);const root=new T.Group();root.position.copy(base);root.quaternion.setFromUnitVectors(this.v(0,0,1),normal);parent.add(root);const isFloor=axis===1&&sign===-1,isRock=!isFloor&&(roomIndex%3!==1||axis===0);const addPanel=(u,v,w,h)=>{const block=this.box(root,[u,v,0],[w,h,.8],isRock?this.materials.rock:this.materials.armor);wallList.push(block);if(isRock){const geo=new T.PlaneGeometry(w,h,Math.ceil(w/1.8),Math.ceil(h/1.8)),p=geo.attributes.position,uv=geo.attributes.uv;for(let i=0;i<p.count;i++){const x=p.getX(i)+u,y=p.getY(i)+v;const raised=.48+Math.abs(this.noise(x+center.x,y+center.y,center.z))*1.2;p.setZ(i,raised);uv.setXY(i,x/13,y/13);}geo.computeVertexNormals();const surface=this.mesh(root,geo,this.materials.rock,this.v(u,v,0));wallList.push(surface);}else{for(let x=-w/2+3;x<w/2;x+=6){const seam=this.box(root,[u+x,v,.43],[.035,h,.055],this.materials.black);seam.castShadow=false;}for(let y=-h/2+6;y<h/2;y+=6)this.box(root,[u,v+y,.44],[w,.035,.06],this.materials.black);}};
    if(opening){addPanel(-13.5,0,9,36);addPanel(13.5,0,9,36);addPanel(0,-13.5,18,9);addPanel(0,13.5,18,9);}else addPanel(0,0,36,36);
    // Structural I-beams, bolted collars and small functional guide lamps.
    const perimeter=opening?9.4:16.6;for(const x of [-perimeter,perimeter]){this.box(root,[x,0,1.05],[.8,opening?20:34,1.2],this.materials.armor);this.box(root,[x,0,1.7],[1.4,opening?20:34,.18],this.materials.steel);for(let y=-perimeter;y<=perimeter;y+=5){this.box(root,[x,y,1.9],[1.9,.7,.32],this.materials.rubber);for(const bx of[-.62,.62])this.cylinder(root,[x+bx,y,2],[x+bx,y,2.17],.12,this.materials.steel,6);}}
    if(opening){for(const y of[-9.4,9.4]){this.box(root,[0,y,1.1],[20,1,1.25],this.materials.armor);for(const x of[-7,-5,-3,-1,1,3,5,7]){const s=this.box(root,[x,y,1.78],[.65,.65,.035],this.materials.yellow);s.rotation.z=-.55;}}
      for(const x of[-9.3,9.3]){this.box(root,[x,5,1.83],[.46,3.2,.35],this.materials.black);this.box(root,[x,5,2.03],[.18,2.7,.08],this.emissive(0xb3cbbf,2.4));}
      this.label(root,'SECTOR '+String(roomIndex+1).padStart(2,'0'),[0,12,2.2],9,2);}
    else if(!isFloor){this.box(root,[0,-9,1.8],[9,4,1.8],this.materials.rubber);for(let i=0;i<12;i++)this.box(root,[-4+i*.73,-9,2.85],[.16,3.5,.22],this.materials.steel);this.label(root,roomIndex%2?'EXTRACTION / 09':'RESTRICTED / ORE HANDLING',[0,8,2.5],12,2.5);}
    return root;
  }
  label(parent,text,pos,w,h){if(typeof document==='undefined'||!document.createElement)return;const T=this.T,c=document.createElement('canvas');c.width=768;c.height=128;const ctx=c.getContext('2d');if(!ctx?.fillText)return;ctx.fillStyle='#111719';ctx.fillRect(0,0,768,128);ctx.fillStyle='#c0b28b';ctx.fillRect(0,0,12,128);ctx.font='bold 42px monospace';ctx.fillText(text,30,75);ctx.fillStyle='#676d68';ctx.font='17px monospace';ctx.fillText('AUTONOMOUS INDUSTRIAL SYSTEMS',32,108);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.MeshBasicMaterial({map:tex,transparent:true,opacity:.84});m.userData.ownedTexture=tex;this.mesh(parent,new T.PlaneGeometry(w,h),m,this.v(...pos));}
  room(parent,center,index){const T=this.T,r=new T.Group();r.position.copy(center);parent.add(r);const m=this.materials;
    // Two massive ceiling gantry beams carry crane motors and service conduits.
    for(const z of[-11,11]){this.box(r,[0,14.9,z],[32,1.35,1.3],m.armor);this.box(r,[0,14,z],[32,.18,2.3],m.steel);for(const x of[-13,13]){this.box(r,[x,13,z],[3.2,3.2,3.2],m.rubber);this.cylinder(r,[x,12.3,z-1.8],[x,12.3,z+1.8],.8,m.brass,12);}}
    for(const x of[-14,14]){this.cylinder(r,[x,15,-16],[x,15,16],.55,m.steel);this.cylinder(r,[x+1,15.4,-16],[x+1,15.4,16],.22,m.brass);for(let z=-14;z<=14;z+=7){this.box(r,[x,15,z],[2,1.8,.45],m.rubber);}}
    // Suspended work fixtures; actual point lights provide readable pools of light.
    for(const z of[-9,9]){this.box(r,[0,12.7,z],[6,.65,2],m.rubber);this.box(r,[0,12.3,z],[5.2,.08,1.25],this.emissive(index%2?0xd1c5a1:0xb3c8d0,2.4));for(const x of[-2,2])this.cylinder(r,[x,13,z],[x,15.5,z],.045,m.steel);}
    const lamp=new T.PointLight(index%2?0xffdfb0:0xc6dce3,1100,62,2);lamp.position.copy(center).add(this.v(0,10,0));parent.add(lamp);this.roomLights.push(lamp);lamp.visible=false;
    // Machinery stays against the shell so the flight volume remains clear.
    for(const sign of[-1,1]){const p=[sign*14,-12,sign*10];this.box(r,p,[4,8,5],m.armor);this.obstacles.push({min:center.clone().add(this.v(p[0]-2.5,-16,p[2]-3)),max:center.clone().add(this.v(p[0]+2.5,-7.5,p[2]+3))});this.box(r,[p[0],-7.8,p[2]],[4.6,.7,5.6],m.steel);for(let i=0;i<5;i++)this.box(r,[p[0]-sign*2.2,-10+i*.7,p[2]],[.12,.3,3.9],m.black);this.cylinder(r,[p[0],-11,p[2]-3],[p[0],-11,p[2]+3],1.6,m.rubber,14);for(const z of[-2.5,2.5])this.cylinder(r,[p[0],-11,p[2]+z-.15],[p[0],-11,p[2]+z+.15],1.8,m.steel,16);}
    // Bedrock ribs and exposed ore fragments interrupt the manufactured silhouette.
    for(let i=0;i<12;i++){const x=(i%2?1:-1)*(15.5+Math.random()),z=-15+(i%6)*6;const rock=this.mesh(r,new T.IcosahedronGeometry(1,1),m.rock,this.v(x,-15.5,z),this.v(1.1+Math.random(),1+Math.random()*1.5,1.5));rock.rotation.set(i*.3,i,.2);}
    for(let i=0;i<3;i++){const z=-12+i*12;this.cable(r,[[-15,13,z],[-13,9,z+2],[-15,4,z+1],[-15,-8,z]],.12,m.rubber);}
    this.dustCloud(parent,center,120,33,0x9ca4a1,.075);return r;
  }
  cable(parent,points,r=.08,mat=this.materials.rubber){const T=this.T,path=new T.CatmullRomCurve3(points.map(p=>this.v(...p)));return this.mesh(parent,new T.TubeGeometry(path,24,r,6,false),mat);}
  tunnel(parent,a,b){const T=this.T,delta=b.clone().sub(a),axis=delta.x?0:delta.y?1:2,other=[0,1,2].filter(i=>i!==axis),center=a.clone().add(b).multiplyScalar(.5),g=new T.Group();g.position.copy(center);g.quaternion.setFromUnitVectors(this.v(0,0,1),delta.clone().normalize());parent.add(g);for(const z of[-5,0,5]){for(const x of[-8.45,8.45])this.box(g,[x,0,z],[.32,17.1,.7],this.materials.steel);for(const y of[-8.45,8.45])this.box(g,[0,y,z],[17.1,.32,.7],this.materials.steel);for(const s of[-1,1]){const bevel=this.box(g,[s*7.7,7.7,z],[2,.5,.7],this.materials.armor);bevel.rotation.z=s*.78;}}
    for(const x of[-7,7]){this.cylinder(g,[x,7,-7.4],[x,7,7.4],.2,this.materials.brass);this.cylinder(g,[x+.5,7.5,-7.4],[x+.5,7.5,7.4],.13,this.materials.rubber);this.box(g,[x,5.5,0],[.32,.18,3.2],this.emissive(0xc7b887,1.8));}
    return g;
  }
  reactor(parent,pos){const T=this.T,m=this.materials,g=new T.Group();g.position.copy(pos);parent.add(g);this.cylinder(g,[0,-13,0],[0,-10,0],7.4,m.armor,16);this.cylinder(g,[0,-10,0],[0,-7,0],5.9,m.rubber,16);this.cylinder(g,[0,9,0],[0,12,0],7,m.armor,16);const core=this.mesh(g,new T.CylinderGeometry(2.8,2.8,12,24),this.emissive(0xffb774,2.8));
    for(let i=0;i<8;i++){const a=i*Math.PI/4,x=Math.sin(a)*5,z=Math.cos(a)*5;this.cylinder(g,[x,-10,z],[x,10,z],.58,m.steel,10);this.cylinder(g,[x*1.22,-13,z*1.22],[x*1.22,12,z*1.22],.18,m.brass,8);for(const y of[-8,8]){const plate=this.box(g,[x,y,z],[2.5,3.6,1],m.armor);plate.rotation.y=a;}this.box(g,[x*.73,0,z*.73],[.22,9,.22],this.emissive(0xe59652,1.5));}
    for(const y of[-7,-3,3,7]){const ring=this.mesh(g,new T.TorusGeometry(5.8,.42,8,48),m.steel,this.v(0,y,0));ring.rotation.x=Math.PI/2;}
    const shield=this.mesh(g,new T.CylinderGeometry(6.1,6.1,17,32,1,true),new T.MeshBasicMaterial({color:0x6dacc3,transparent:true,opacity:.09,side:T.DoubleSide}));this.label(g,'CORE / PRESSURE VESSEL',[0,-11,7.7],7,1.4);return {group:g,core,shield};
  }
  pickup(parent,pos,type,tint){
    const T=this.T,m=this.materials,g=new T.Group();g.position.copy(pos);parent.add(g);
    const weapon=type==='cannon',ammo=type==='cannonAmmo',color=tint??(type==='shield'?0x96c7e1:type==='missile'?0xd9ab67:0xb7c792);
    this.box(g,[0,0,0],weapon?[3.6,1.7,2.6]:[2.6,1.5,1.8],m.armor);
    this.box(g,[0,.8,0],weapon?[3.9,.2,2.8]:[2.9,.2,2],m.rubber);
    for(const x of[-1,1])this.box(g,[x*(weapon?1.65:1),0,0],[.2,1.7,weapon?2.8:2],m.steel);
    const light=this.emissive(color,2.5);this.box(g,[0,.15,weapon?1.4:1],[.9,.25,.05],light);
    if(weapon){
      this.box(g,[0,1.35,0],[1.1,.8,1.8],m.steel);
      for(const x of[-.38,.38]){this.cylinder(g,[x,1.4,-.4],[x,1.4,-2.4],.23,m.steel,10);this.cylinder(g,[x,1.4,-2.1],[x,1.4,-2.5],.15,light,8);}
      for(const x of[-1.4,1.4])this.box(g,[x,1,0],[.15,.25,2.2],light);
    }else if(ammo){
      for(const x of[-.7,0,.7]){this.cylinder(g,[x,.95,-.6],[x,.95,.6],.22,m.steel,8);this.cylinder(g,[x,.95,.4],[x,.95,.65],.23,light,8);}
    }else if(type==='shield'){
      const ring=new T.Mesh(new T.TorusGeometry(1.8,.09,6,32),light);ring.rotation.x=Math.PI/2;ring.position.y=1.4;g.add(ring);
      for(const x of[-1.05,1.05])this.box(g,[x,.1,1.02],[.15,1.15,.08],light);
    }else if(type==='missile')for(const x of[-.7,0,.7])this.cylinder(g,[x,1,-.65],[x,1,.65],.18,m.brass,8);
    return g;
  }
  cockpit(camera){const T=this.T,m=this.materials,g=new T.Group();camera.add(g);const armor=m.armor.clone();armor.color.setHex(0x384044);armor.userData.shared=true;const screen=this.emissive(0x496b67,.5);
    for(const s of[-1,1]){const rail=this.box(g,[s*.95,-.63,-1.13],[.2,.19,1.9],armor);rail.rotation.z=-s*.22;const pillar=this.box(g,[s*1.12,-.27,-1.2],[.05,.82,.12],m.rubber);pillar.rotation.z=-s*.3;this.box(g,[s*.76,-.52,-1.82],[.19,.15,.7],armor);for(const x of[-.065,.065])this.cylinder(g,[s*.76+x,-.48,-1.9],[s*.76+x,-.48,-2.22],.025,m.steel,8);this.box(g,[s*.58,-.69,-1.1],[.35,.15,.32],armor);const panel=this.box(g,[s*.58,-.603,-1.1],[.27,.009,.22],screen);panel.rotation.x=.12;for(let i=0;i<5;i++)this.box(g,[s*.75,-.59,-.85-i*.08],[.02,.025,.015],this.emissive(i===0?0xb47742:0x91a6a0,.7));this.cable(g,[[s*1,-.6,-.8],[s*.87,-.55,-1.1],[s*.85,-.65,-1.7]],.018,m.rubber);}
    this.box(g,[0,-.83,-1.08],[2,.23,.4],armor);this.box(g,[0,-.7,-1.1],[.35,.06,.23],m.rubber);this.box(g,[0,-.665,-1.1],[.24,.012,.15],screen);return g;
  }
  dustCloud(parent,center,count=100,size=30,color=0x9ca4a1,opacity=.1){const T=this.T,geo=new T.BufferGeometry(),pos=new Float32Array(count*3);for(let i=0;i<count;i++){pos[i*3]=(Math.random()-.5)*size;pos[i*3+1]=(Math.random()-.5)*size;pos[i*3+2]=(Math.random()-.5)*size;}geo.setAttribute('position',new T.BufferAttribute(pos,3));const mat=new T.PointsMaterial({color,size:.055,transparent:true,opacity,depthWrite:false});const points=new T.Points(geo,mat);points.position.copy(center);parent.add(points);this.dust.push(points);}
  reset(){this.dust=[];this.effects=[];this.moving=[];this.obstacles=[];this.roomLights=[];}
  burst(parent,pos,scale,color){if(scale<.6)return;const T=this.T;if(!this.flareTexture){const n=64,data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const d=Math.hypot((x-n/2)/(n/2),(y-n/2)/(n/2)),i=(y*n+x)*4;data[i]=data[i+1]=data[i+2]=255;data[i+3]=Math.max(0,Math.pow(1-Math.min(1,d),2.2)*255);}this.flareTexture=new T.DataTexture(data,n,n);this.flareTexture.needsUpdate=true;}for(let i=0;i<6;i++){const smoke=i>1,m=new T.SpriteMaterial({map:this.flareTexture,color:smoke?0x41403a:color,transparent:true,opacity:smoke?.24:.9,blending:smoke?T.NormalBlending:T.AdditiveBlending,depthWrite:false});const sprite=new T.Sprite(m);sprite.position.copy(pos).add(this.v((Math.random()-.5)*scale,(Math.random()-.5)*scale,(Math.random()-.5)*scale));sprite.scale.setScalar(scale*(smoke?4:3));parent.add(sprite);this.effects.push({sprite,life:smoke?2.5:.25,max:smoke?2.5:.25,smoke,scale});}}
  updateLighting(pos){
    const near=[...this.roomLights].sort((a,b)=>a.position.distanceToSquared(pos)-b.position.distanceToSquared(pos)).slice(0,4);
    for(const light of this.roomLights)light.visible=near.includes(light);
  }
  blocked(p,r){for(const b of this.obstacles){const closest=p.clone().clamp(b.min,b.max);if(closest.distanceToSquared(p)<r*r)return true;}return false;}
  batchEnvironment(root){const T=this.T,groups=new Map();root.updateMatrixWorld(true);root.traverse(o=>{if(!o.isMesh||o.material.transparent||Array.isArray(o.material))return;const e=o.matrixWorld.elements,key=o.material.uuid+':'+[e[12],e[13],e[14]].map(n=>Math.round(n/50)).join(',');if(!groups.has(key))groups.set(key,{mat:o.material,objects:[]});groups.get(key).objects.push(o);});for(const {mat,objects}of groups.values()){if(objects.length<3)continue;const vertices=[],normals=[],uvs=[];for(const o of objects){const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(o.matrixWorld);const p=g.attributes.position,n=g.attributes.normal,uv=g.attributes.uv;for(let i=0;i<p.count;i++){vertices.push(p.getX(i),p.getY(i),p.getZ(i));normals.push(n?.getX(i)||0,n?.getY(i)||1,n?.getZ(i)||0);uvs.push(uv?.getX(i)||0,uv?.getY(i)||0);}g.dispose();o.visible=false;}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));const merged=new T.Mesh(g,mat);merged.receiveShadow=true;merged.castShadow=true;merged.userData.batch=true;root.add(merged);}}
  update(t,dt){for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.life-=dt;e.sprite.scale.multiplyScalar(1+dt*(e.smoke?.5:4));e.sprite.material.opacity=(e.smoke?.24:.9)*Math.max(0,e.life/e.max);e.sprite.position.y+=dt*(e.smoke?.8:0);if(e.life<=0){e.sprite.parent?.remove(e.sprite);e.sprite.material.dispose();this.effects.splice(i,1);}}for(const d of this.dust){d.rotation.y=Math.sin(t*.035)*.03;d.position.y+=Math.sin(t*.2)*dt*.025;}}
}

export class CinematicPass {
  constructor(T,renderer,width,height){this.T=T;this.renderer=renderer;this.target=new T.WebGLRenderTarget(width,height,{type:T.HalfFloatType,depthBuffer:true});this.target.texture.colorSpace=T.LinearSRGBColorSpace;this.scene=new T.Scene();this.camera=new T.OrthographicCamera(-1,1,1,-1,0,1);this.uniforms={image:{value:this.target.texture},resolution:{value:new T.Vector2(width,height)},clock:{value:0},strength:{value:1}};this.material=new T.ShaderMaterial({uniforms:this.uniforms,depthTest:false,depthWrite:false,toneMapped:false,vertexShader:'varying vec2 uv0;void main(){uv0=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`precision highp float;uniform sampler2D image;uniform vec2 resolution;uniform float clock;uniform float strength;varying vec2 uv0;
vec3 bright(vec2 uv){vec3 c=texture2D(image,uv).rgb;return max(c-vec3(1.0),0.0);}
vec3 aces(vec3 x){return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.,1.);}
void main(){vec2 uv=uv0,px=1./resolution;vec3 c=texture2D(image,uv).rgb;vec3 bloom=vec3(0.);for(int i=0;i<8;i++){float a=float(i)*.785398;vec2 v=vec2(cos(a),sin(a));bloom+=bright(uv+v*px*3.)*.032;bloom+=bright(uv+v*px*9.)*.021;bloom+=bright(uv+v*px*22.)*.008;}c+=bloom*strength;c=aces(c*1.12);float vignette=1.-.32*pow(length((uv-.5)*vec2(1.1,1.)),1.4);c*=vignette;float grain=fract(sin(dot(uv*resolution+fract(clock)*1.7,vec2(12.9898,78.233)))*43758.5453)-.5;c+=grain*.008;c=pow(max(c,0.),vec3(1./2.2));gl_FragColor=vec4(c,1.);}`});this.scene.add(new T.Mesh(new T.PlaneGeometry(2,2),this.material));}
  resize(w,h){this.target.setSize(w,h);this.uniforms.resolution.value.set(w,h);}
  render(scene,camera,t){const r=this.renderer,tm=r.toneMapping;r.toneMapping=this.T.NoToneMapping;r.setRenderTarget(this.target);r.clear();r.render(scene,camera);r.setRenderTarget(null);this.uniforms.clock.value=t;r.toneMapping=tm;r.render(this.scene,this.camera);}
}
